syntax = "proto3";

package atores;

service AtorService {
    rpc ListarAtores(ListarAtoresRequest) returns (ListarAtoresResponse);
    rpc ObterAtorPorId(ObterAtorPorIdRequest) returns (ObterAtorPorIdResponse);
    rpc CriarAtor(CriarAtorRequest) returns (CriarAtorResponse);
    rpc AtualizarAtor(AtualizarAtorRequest) returns (AtualizarAtorResponse);
    rpc DeletarAtor(DeletarAtorRequest) returns (DeletarAtorResponse);
}

message Ator {
    string id = 1;
    string nome = 2;
    string data_nascimento = 3; // formato: YYYY-MM-DD
}

message ListarAtoresRequest {}

message ListarAtoresResponse {
    repeated Ator atores = 1;
}

message ObterAtorPorIdRequest {
    string id = 1;
}

message ObterAtorPorIdResponse {
    Ator ator = 1;
}

message CriarAtorRequest {
    string nome = 1;
    string data_nascimento = 2;
}

message CriarAtorResponse {
    Ator ator = 1;
}

message AtualizarAtorRequest {
    string id = 1;
    string nome = 2;
    string data_nascimento = 3;
}

message AtualizarAtorResponse {
    Ator ator = 1;
}

message DeletarAtorRequest {
    string id = 1;
}

message DeletarAtorResponse {
    bool success = 1;
}