syntax = "proto3";

package generos;

service GeneroService {
    rpc ListarGeneros(ListarGenerosRequest) returns (ListarGenerosResponse);
    rpc ObterGeneroPorId(ObterGeneroPorIdRequest) returns (ObterGeneroPorIdResponse);
    rpc CriarGenero(CriarGeneroRequest) returns (CriarGeneroResponse);
    rpc AtualizarGenero(AtualizarGeneroRequest) returns (AtualizarGeneroResponse);
    rpc DeletarGenero(DeletarGeneroRequest) returns (DeletarGeneroResponse);
}

message Genero {
    string id = 1;
    string nome = 2;
}

message ListarGenerosRequest {}

message ListarGenerosResponse {
    repeated Genero generos = 1;
}

message ObterGeneroPorIdRequest {
    string id = 1;
}

message ObterGeneroPorIdResponse {
    Genero genero = 1;
}

message CriarGeneroRequest {
    string nome = 1;
}

message CriarGeneroResponse {
    Genero genero = 1;
}

message AtualizarGeneroRequest {
    string id = 1;
    string nome = 2;
}

message AtualizarGeneroResponse {
    Genero genero = 1;
}

message DeletarGeneroRequest {
    string id = 1;
}

message DeletarGeneroResponse {
    bool success = 1;
}